<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.marquee/1.3.1/jquery.marquee.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
<style>
.marquee {
    width: 100%;
    overflow: hidden;
    color: black;
}
ul.marquee li{
    display: inline-block;
    padding: 10px 20px;
    font-size: 20px;
}

.administrator_banner_image{
	background-image: url(/img/NRG-banner.png);
    height :80vh;
    width:100%;
    background-repeat: no-repeat;
    background-position: center center;
    background-size: 100% 100%;
}
*{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    }


/*-------------------------- use code----------------------------------------- */
.nrg_main_right{
    width: 100%;
    height: 100%;
    background-color: #f9f9f9;
    padding: 0 16px;
    padding-bottom: 48px;
}
.nrg_main_right_box{
    background-color: #34ABAA;
    transition: 0.3s;
    position: relative;
    width: 32%;
    padding: 16px;
    border-radius: 20%;
}
.nrg_main_right_box:hover{
    box-shadow: 0 0 20px 0 rgb(0 0 0 / 30%);
}

.nrg_main_right_box_parent .nrg_main_right_box:nth-child(2){
    background-color: #267683;
    border-radius: 14%;
    
}
.rightbox_clip_info, .rightbox_clip_info2{ 
    color: #267683!important;
    position: absolute;
    width: 16px;
    bottom: -15%;
    right: 25%;
}

/* .nrg_main_right_box_parent .nrg_main_right_box:nth-child(2):hover i{
    color: #00FF00;
} */
.nrg_main_right_box_parent .nrg_main_right_box:nth-child(3){
    background-color: #EB8E27;
    border-radius: 14%;
}
.rightbox_clip_info2{ 
    color: #EB8E27!important;
}
/* .nrg_main_right_box_parent .nrg_main_right_box:nth-child(3):hover i{
    color: #FFFF00;
} */



.nrg_main_right_box i{
    font-size: 64px;
    color: #FFF;
    margin-top: auto;
    margin-left: 8px;
}

.nrg_main_right_box_parent .nrg_main_right_box:nth-child(1)  p span{
    color: #FFF;
    font-size: 19.2px;
    line-height: 150%; 
}
.nrg_main_right_box{
    color: #FFF;
    font-size: 19.2px;
    font-weight: 500;
}
.custom_num{
    font-weight: 600;
    margin-left: 4.8px;
}

.nrg_main_right_box_parent{
    display: flex;
    justify-content: space-between;
}


.nrg_main_right_box_head{
    border-bottom: 1px solid #FFF;
    padding: 12.8px;
}

.custom_price{
    display: block;
    text-align: center;
    font-size: 40px;
    margin-top: 8px;
}


.nrg_main{
    width: 100%;
    height: 100%;
    display: flex;
    /* align-items: center; */
    /* justify-content: center; */
    margin-top: 48px;
    
}

.nrg_main_parent{
    width: 100%;
}
.nrg_main_child{
    width: 100%;
    height: 100%;
    display: flex;
    /* justify-content: center; */
}
.column_div{
    border: 1px solid #00C0EF;
    border-bottom: none;
}

.column_div ul li{
    list-style: none;
    text-align: center;
    text-transform: capitalize;
    border-bottom: 1px solid #00C0EF;
    vertical-align: middle;
    font-size: 16px;
    padding: 1.6 8px;
}
.column_div ul li span > span{
    text-align: right;
    font-size: 13.6px;
}
.person ul li p{
    text-align: left;
    font-size: 16px;
    line-height: 16px;
    font-weight: 500;
    margin-top: 24px;
    margin-left: 8px;
}

.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(2){
  color: red;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(3){
    color: blue;
  }
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(4){
    color: green;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(5){
    color: orange;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(6){
    color: violet;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(7){
    color: purple;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(8){
    color: gray;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(9){
    color: mediumseagreen;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(10){
    color: brown;
}
.nrg_main_child .parent_column_div:nth-child(2) .column_div ul li:nth-child(11){
    color: darkblue;
}

.column_div > P{
    color: #FFF;
    background: #00C0EF;
    text-align: center;
    vertical-align: middle;
    font-weight: 500;
}
.parent_column_div{
    width: 19%;
}
.person{
    width: 24%;
}

.column_div > p{
    padding: 16px 24px;
    display: flex;
    flex-direction: column;
}

.custom_person_details_parent{
    padding: 11.2px 1.px;
}
.custom_person_details{
    display: flex;
    align-items: center;
}
.custom_person_details img{
    width: 80px;
    height: 80px;
    border-radius: 50%;
    border: 3px solid #00a65a;
}
.custom_person_details span{
    margin-left: 8px;
    font-size: 24px;
    font-weight: 600;
    text-decoration: underline;
}
.transactions_person{
    display: flex;
}
.transactions_person img{
    width: 28.8px;
    height: 28.8px;
    margin-top: 16px;
}

.levels_transaction{
    display: flex;
    justify-content: end;
}
.levels_transaction img{
    width: 14.4px;
    height: 14.4px;
}




@media only screen and (max-width: 768px){

    .top_bar{
        padding-left: 64px!important;
    }
    .nrg_main_right_box_parent{
        display: block;
    }

    .nrg_main_left {
        width: 30%;
    }
    .nrg_main_right {
        width: 70%;
        padding: 0 8px;
    }
    .nrg_main_right_box {
        padding: 6.4px;
    }
    .nrg_main_right_box p span {
        font-size: 12.8px;
        line-height: 150%;
    }
    .nrg_main_right_box i {
        font-size: 48px;
        margin-left: 32px;
    }
    .nrg_main_right_box_flex > span{
        width: 70%;
    }
    .nrg_main_right_box_parent .nrg_main_right_box:nth-child(2) {
        margin: 16px 0;
    }
 
}


</style>
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <?php
                    //if(!empty($announcements)):
                    ?>
                    <!--<h4>Announcements</h4><br/>
                    <ul class='marquee'>
                        <?php $i=0;foreach($announcements as $announcement): 
                            if(!empty($myNotification)){
                                    if(in_array($announcement['id'],$myNotification))
                                        continue;
                                    }
                        ?>
                            <?php $i++; ?>
                            <li><?php echo $i; ?>. <?php echo $announcement['message_text'];  ?></li>
                        <?php endforeach; ?>
                    </ul>-->
                    <?php
                    //endif;
                    ?>
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="baneer" style="display:none">
                    
                    
                       <div class=" administrator_banner_image">
                           
                       </div>
                    

                      
                    
                </section>
                <div class="nrg_main_right">
            <div class="nrg_main_right_box_parent" style="margin-top: 16px;">
                <div class="nrg_main_right_box">
                    <div style="display: flex; justify-content: center;"><img src="/400_F_350548601_TBrddMrW8liLvqMVl8HNLwymhrQRRJ8l-removebg-preview.png" alt="" style="width: 80px;"></div> 
                    <div style="display: flex;">
                        <span>
                            <p style="display: flex; align-items: center;">
                                <img src="/open.png" alt="" style="width: 32px;">  <span style="margin-left: 8px;">Open Transaction :</span><span class="custom_num">5</span>
                            </p>
                            <p style="display: flex; align-items: center;">
                                <img src="/pending.png" alt="" style="width: 32px;">  <span style="margin-left: 8px;">Pending Transaction :</span><span class="custom_num">7</span>
                            </p>
                            <p style="display: flex; align-items: center;">
                                <img src="/close.png" alt="" style="width: 32px;">  <span style="margin-left: 8px;">Closed Transaction :</span><span class="custom_num">15</span>
                            </p>
                        </span>
                        
                    </div>

                </div>

                <div class="nrg_main_right_box">
                    <!-- <i class="fad fa-info-circle" style="display: block;text-align: center;"></i> -->
                   <div style="display: flex; justify-content: center;"><img src="/open.png" alt="" style="width: 80px;"></div> 
                    <div style="display: flex;">
                        <span>
                            <p>
                                <span>Your estimated earnings from your affiliates open transactions is</span>
                            </p>
                            <p>
                                <span class="custom_price">USD 200</span>
                            </p>

                        </span>
                    </div> 
                    <i class="fas fa-caret-down rightbox_clip_info"></i>            

                </div>

                <div class="nrg_main_right_box">
                    <!-- <i class="fad fa-info-circle" style="display: block;text-align: center;"></i> -->
                   <div style="display: flex; justify-content: center;"><img src="/pending.png" alt="" style="width: 64px;"></div> 
                    <div style="display: flex;">
                        <span>
                            <p>
                                <span>Your estimated earnings from your affiliates pending transactions is</span>
                            </p>
                            <p>
                                <span class="custom_price">USD 200</span>
                            </p>

                        </span>
                    </div>
                    <i class="fas fa-caret-down rightbox_clip_info2"></i>

                </div>

            </div>

            <div class="nrg_main">
                <div class="nrg_main_parent">
                    <div class="nrg_main_child">
                        <div class="parent_column_div person">
                            <div class="column_div">
                                <p><i class="fas fa-user" style="font-size: 34.6px;"></i> </p>
                                <ul>
                                    <li>
                                        <div class="custom_person_details_parent">
                                            <div class="custom_person_details"><img src="/thumb-upyoRUq8.jpg"
                                                    alt=""> <span><?php echo $username;?></span></div>
                                            <div class="transactions_person"><img src="/open.png" alt="">
                                                <p>Open transactions :- 3</p>
                                            </div>
                                            <div class="transactions_person"><img src="/pending.png" alt="">
                                                <p>Pending transactions :- 5</p>
                                            </div>
                                            <div class="transactions_person"><img src="/close.png" alt="">
                                                <p>Closed transactions :- 8</p>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="parent_column_div level">
                            <div class="column_div">
                                <p><i class="fas fa-users"></i> LEVEL 1</p>
                                <ul>
                                    <?php foreach($data as $level){ ?>
                                    <li><?php echo $level['firstname']; ?>
                                        <div class="levels_transaction">
                                            <span> <img src="/open.png" alt=""> <span>1/</span>  
                                                <img src="/pending.png" alt=""> <span> 3/</span>
                                                    <img src="/close.png" alt=""> <span>7</span>
                                                </span>
                        
                                        </div>
                                    </li>
                                   <?php } ?>
                                </ul>
                            </div>
                        </div>

                        <div class="parent_column_div level">
                            <div class="column_div">
                                <p><i class="fas fa-users"></i> LEVEL 2</p>
                                <ul>
                                <?php foreach($data2 as $level2){ ?>
                                    <li><?php echo $level2['firstname']; ?>
                                        <div class="levels_transaction">
                                            <span> <img src="/open.png" alt=""> <span>1/</span>  
                                                <img src="/pending.png" alt=""> <span> 3/</span>
                                                    <img src="/close.png" alt=""> <span>7</span>
                                                </span>
                        
                                        </div>
                                </li>
                                   <?php } ?>
                                </ul>
                            </div>
                        </div>

                        <div class="parent_column_div level">
                            <div class="column_div">
                                <p> <i class="fas fa-users"></i> LEVEL 3</p>
                                <ul>
                                <?php foreach($data3 as $level3){ ?>
                                    <li><?php echo $level3['firstname']; ?>
                                        <div class="levels_transaction">
                                            <span> <img src="/open.png" alt=""> <span>1/</span>  
                                                <img src="/pending.png" alt=""> <span> 3/</span>
                                                    <img src="/close.png" alt=""> <span>7</span>
                                                </span>
                        
                                        </div>
                                </li>
                                   <?php } ?>
                                </ul>
                            </div>
                        </div>

                        <div class="parent_column_div level">
                            <div class="column_div">
                                <p><i class="fas fa-users"></i> LEVEL 4</p>
                                <ul>
                                <?php foreach($data4 as $level4){ ?>
                                    <li><?php echo $level4['firstname']; ?>
                                        <div class="levels_transaction">
                                            <span> <img src="/open.png" alt=""> <span>1/</span>  
                                                <img src="/pending.png" alt=""> <span> 3/</span>
                                                    <img src="/close.png" alt=""> <span>7</span>
                                                </span>
                        
                                        </div>
                                </li>
                                   <?php } ?>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
                   

            
              
                
<script>
$(function () {
    $('.marquee').marquee({
        duration: 15000,
        duplicate: true,
        // pauseOnHover: true,
    });
});

</script>